version: "3.3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - fastapi
  web:
    build: ./next-app
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - ./next-app/:/usr/app/
      # - ./next-app/packages.json:/usr/app/packages.json
      - dependencies:/usr/app/node_modules
  fastapi:
    build: ./fastapi-app
    container_name: fastapi
    ports: 
      - "8000:8000"
    volumes:
      - ./fastapi-app/app/:/code/app/
      - ./fastapi-app/requirements.txt:/code/requirements.txt
      # - fastapi_packages:/usr/local/lib/python3.10/site-packagesd
volumes:
  dependencies:
  fastapi_packages: